title: WorldMachine wiki
description: Unofficial WorldMachine wiki in Chinese
theme: just-the-docs

url: https://ALingll.github.io/wm-wiki-zh

aux_links:
  Template Repository: https://github.com/ALingll/wm-wiki-zh

# 开启搜索
search_enabled: true
search:
  heading_level: 2
  previews: 3
  rel_url: true
  button: true

# 设置侧边导航
just_the_docs:
  navigation: _data/navigation.yml
  show_toc: true
  toc_heading: "快速定位"

toc:
  min_level: 2
  max_level: 3

sass:
  style: compressed

